CREATE TABLE USER (
   ID BINARY(255) NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   PASSWORD VARCHAR(1000),
   CREATED DATE,
   MODIFIED DATE,
   LAST_LOGIN TIMESTAMP,
   TOKEN VARCHAR(512) NOT NULL,
   PRIMARY KEY (ID),
   CONSTRAINT UC_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PHONE (
   ID BINARY(255) NOT NULL,
   DDD INTEGER NOT NULL,
   NUMBER INTEGER NOT NULL,
   USER_ID BINARY(255),
   PRIMARY KEY (ID),
   FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);